# Generated by Django 4.2.1 on 2023-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursename',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='Studentname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
